name: image-test

on: 
    pull_request:
      types: [opened, reopened]
    push:
      branches:
        - '**'
      paths-ignore:
        - 'CHANGELOG.md'
        - 'package.json'
        - 'package-lock.json'
    workflow_dispatch: # Evento que aciona o fluxo de trabalho manualmente
      inputs: # Define os inputs do fluxo de trabalho
        name: # Define o input "name"
          description: 'Trigger manual do Workflow' # Descrição do input

jobs: 
    docker-buid:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                token: ${{ secrets.ACTIONS_TOKEN }}

            - name: Install and Build
              run: |
                npm install

            - name: Configuring Git Account
              run: |
                git config --global user.email "pipelines@toolboxdevops.cloud"
                git config --global user.name "Toolbox Automation"

            - name: Docker Login
              # You may pin to the exact commit or the version.
              # uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
              uses: docker/login-action@v3.2.0
              with:
                username: toolboxdevopsplayground
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build e Push no Azure Container Registry
              run: |
                VERSION=$(jq -r '.version' package.json)
                docker build -t toolboxdevopsplayground/hello-world-nodejs:$VERSION .
